proc printHelp*() =
  echo "\nA Java version manager and build tool written in Nim"
  echo "\nUsage: jv <command> [options]"
  echo "\nCommands:"
  echo "  init                       Initialize a new Java project with Gradle"
  echo "  compile <javaFile>         Compile a Java file"
  echo "  execute <className>        Execute a compiled Java class"
  echo "  manage <subcommand> [...]  Manage Java versions and tools"
  echo "    subcommands:"
  echo "      search                 List available Java versions to install"
  echo "      list                   List currently installed Java versions"
  echo "      current                Show currently active Java version"
  echo "      install <version>      Install a Java version"
  echo "      uninstall <version>    Uninstall a Java version"
  echo "      set <version>          Set the active Java version"
  echo "      setup                  Install a version manager (Jabba/jEnv)"
  echo "  test                       Run all tests in the tests/ directory"
  echo "  help                       Show this help message"
  echo "  version                    Show jv version\n"
  echo "Examples:"
  echo "  jv init"
  echo "  jv compile App.java"
  echo "  jv execute App"
  echo "  jv manage install openjdk@1.17.0"
  echo "  jv test"
