proc printHelp*() =
  echo "\nA Java version manager and build tool written in Nim"
  echo "\nUsage: jv <command> [options]"
  echo "\nCommands:"
  echo "  compile <javaFile>         Compile a Java file"
  echo "  execute <className>        Execute a compiled Java class"
  echo "  manage <subcommand> [...]  Manage Java versions and tools"
  echo "    subcommands:"
  echo "      list                   List installed Java versions"
  echo "      install <version>      Install a Java version"
  echo "      set <version>          Set the active Java version"
  echo "      setup                  Install a version manager (Jabba/jEnv)"
  echo "  test                       Run all tests in the tests/ directory"
  echo "  help                       Show this help message\n"
  echo "Examples:"
  echo "  jv compile Hello.java"
  echo "  jv execute Hello"
  echo "  jv manage install 1.11.0-openjdk"
  echo "  jv test"
