name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: stable

    - name: Install dependencies
      run: nimble install -y

    - name: Run tests
      run: |
        nim c -r src/main.nim test